"""Initial migration with Site and RiskScenario models

Revision ID: 10533b7f37f0
Revises: 
Create Date: 2025-08-08 13:24:35.669982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10533b7f37f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_name'), ['name'], unique=False)

    op.create_table('risk_scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('risk_type', sa.String(length=50), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_scenario')
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_name'))

    op.drop_table('site')
    # ### end Alembic commands ###
